# Only for development!

version: "3.7"
services:
    app:
        image: "${IMAGE_NAME}"
        entrypoint: /bin/bash
        depends_on:
            - redis
        volumes:
            - .:/app
        ports:
            - 9000:9000
            - "127.0.0.1:8888:8888" # Restricts notebooks to the host machine
    redis:
        image: redis:5.0.5
        command: redis-server
        volumes:
            - ./docker-volumes/redis:/data
        ports:
            - 6379:6379
networks:
    default:
        external:
            name: taplatform
